{ hostInfo, pkgs, ... }: {
  services = {
    cockpit = {
      enable = true;
      openFirewall = true;
      allowed-origins = [
        "https://${hostInfo.name}:9090"
        "wss://${hostInfo.name}:9090"
        "https://${hostInfo.ipA}:9090"
        "wss://${hostInfo.ipA}:9090"
        "https://${hostInfo.ipB}:9090"
        "wss://${hostInfo.ipB}:9090"
      ];
    };

    pcp = {
      enable = true;
      preset = "standalone";

      # not currently working
      # pmdas.lmsensors = {
      #   domain = 74;
      #   type = "pipe";
      #   flags = "binary";
      #   command =
      #     "pmpython ${pkgs.pcp}/var/lib/pcp/pmdas/lmsensors/pmdalmsensors.python";
      # };
    };

    prometheus.exporters.ipmi = {
      enable = true;
      openFirewall = true;
    };
  };

  # pcp pr currently ignores pmdas option
  environment.etc."pcp/pmcd/pmcd.conf" = {
    text = ''
      #
      # Performance Co-Pilot PMDA Configuration
      # Generated by NixOS - do not edit directly
      #

      # --- Base Platform PMDAs ---
      linux   60      dso     linux_init      ${pkgs.pcp}/var/lib/pcp/pmdas/linux/pmda_linux.so
      pmcd    2       dso     pmcd_init       ${pkgs.pcp}/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so

      # --- Additional PMDAs ---
      lmsensors  74  pipe  binary      ${pkgs.writeShellScript "pmda-lmsensors" ''
        export LD_LIBRARY_PATH="${pkgs.pcp}/lib''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
        export PYTHONPATH="${pkgs.pcp}/lib/python3.13/site-packages''${PYTHONPATH:+:$PYTHONPATH}"
        exec ${pkgs.pcp}/bin/pmpython ${pkgs.pcp}/var/lib/pcp/pmdas/lmsensors/pmdalmsensors.python
      ''}
    '';
    mode = "0644";
  };

  environment.systemPackages = with pkgs; [ lm_sensors ];
}
