#!/usr/bin/env bash

nix run nixpkgs#sops -- --encrypt secrets-raw/01.yaml> secrets/01.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/02.yaml> secrets/02.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/03.yaml> secrets/03.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/04.yaml> secrets/04.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/05.yaml> secrets/05.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/06.yaml> secrets/06.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/07.yaml> secrets/07.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/08.yaml> secrets/08.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/09.yaml> secrets/09.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/10.yaml> secrets/10.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/11.yaml> secrets/11.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/12.yaml> secrets/12.yaml
