#!/usr/bin/env bash

nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-01.yaml> secrets/penelope-01.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-02.yaml> secrets/penelope-02.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-03.yaml> secrets/penelope-03.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-04.yaml> secrets/penelope-04.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-05.yaml> secrets/penelope-05.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-06.yaml> secrets/penelope-06.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-07.yaml> secrets/penelope-07.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-08.yaml> secrets/penelope-08.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-09.yaml> secrets/penelope-09.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-10.yaml> secrets/penelope-10.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-11.yaml> secrets/penelope-11.yaml
nix run nixpkgs#sops -- --encrypt secrets-raw/penelope-12.yaml> secrets/penelope-12.yaml
